[package]
name = "shitd"
version = "0.1.0"
edition = "2021"
description = "A silly CLI for tracking your shit to do"

[dependencies]
clap = {version="4.5.16", features = ["derive"]}
anyhow = "1.0.9"
serde = {"1.0.209", features = ["derive"]}
chrono = {"0.4.38", features = ["serde"] }
